# Generated by Django 4.0.4 on 2022-07-01 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionTrabajosApp', '0002_alter_servicio_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='value',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
    ]
