# Generated by Django 4.0.4 on 2022-07-01 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionTrabajosApp', '0003_servicio_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='monto',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='value',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
