# Generated by Django 4.0.4 on 2022-07-01 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestionTrabajosApp', '0004_alter_servicio_monto_alter_servicio_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('day', models.DateField(default=1)),
                ('month', models.DateField(default=7)),
                ('year', models.DateField(default=2022)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionTrabajosApp.servicio')),
            ],
            options={
                'verbose_name': 'Trabajo',
                'verbose_name_plural': 'Trabajos',
            },
        ),
    ]
