# Generated by Django 4.0.4 on 2022-07-01 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionTrabajosApp', '0005_trabajado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajado',
            name='day',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='trabajado',
            name='month',
            field=models.IntegerField(default=7),
        ),
        migrations.AlterField(
            model_name='trabajado',
            name='year',
            field=models.IntegerField(default=2022),
        ),
    ]
