# Generated by Django 4.0.4 on 2022-07-02 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionTrabajosApp', '0008_alter_trabajado_day_salida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salida',
            name='dia',
            field=models.CharField(default=2, max_length=10),
        ),
        migrations.AlterField(
            model_name='salida',
            name='mes',
            field=models.CharField(default='Julio', max_length=15),
        ),
        migrations.AlterField(
            model_name='salida',
            name='total',
            field=models.IntegerField(default=1400),
        ),
    ]
