# Generated by Django 4.0.4 on 2022-07-03 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionTrabajosApp', '0009_alter_salida_dia_alter_salida_mes_alter_salida_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salida',
            name='total',
            field=models.IntegerField(default=1900),
        ),
    ]
